name: Build and Publish

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-publish:
    uses: swatijha23/github_action_test/.github/workflows/Publish.yml@main
    with:
      node-version: 'lts/*'
      publish-to-npm: true
      s3-path: 'media-agents/browser/test'
      file-to-upload: 'dist/newrelic-video-dash.min.js'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }} 